---
title: "Quantium Task 2: Causal Analysis"
author: "Yihan Yang"
date: "2023-11-27"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r 0. Load libraries, include = FALSE}
library(data.table)
library(ggplot2)
library(tidyr)
library(CausalImpact)
```

```{r}
data <- fread(paste0("/Users/yangyihan/Downloads/","QVI_data.csv"))
#### Set themes for plots
theme_set(theme_bw())
theme_update(plot.title = element_text(hjust = 0.5))
```

```{r}
data[, YEARMONTH := format(DATE, "%Y%m")]
head(data,2)
```
```{r}
measureOverTime <- data[, .(
  totSales = sum(TOT_SALES), # Sum of sales
  nCustomers = uniqueN(LYLTY_CARD_NBR), # Count of unique customers
  nTxn = .N,
  nTxnPerCust = .N / uniqueN(LYLTY_CARD_NBR), # Number of transactions per customer
  nChipsPerTxn = sum(PROD_QTY) / .N, # Chips (assuming 'Quantity') per transaction
  avgPricePerUnit = sum(TOT_SALES) / sum(PROD_QTY) # Average price per unit
), by = .(STORE_NBR, YEARMONTH)][order(STORE_NBR, YEARMONTH)]

```

```{r}
#### Filter to the pre-trial period and stores with full observation periods
storesWithFullObs <- unique(measureOverTime[, .N, STORE_NBR][N == 12, STORE_NBR])
fullobsdata <- measureOverTime[STORE_NBR %in% storesWithFullObs]
```

```{r}
# Use dcast to reshape the data
salesdata <- dcast(fullobsdata,YEARMONTH ~ STORE_NBR, value.var = "totSales")
presalesData <- salesdata[YEARMONTH < 201902]

# View the reshaped dataset
head(presalesData,2)
```

```{r}
start= 1
treatment= 8
end= 10
```

```{r}
#Sales of Store 77
# Compute the correlation matrix excluding the YEARMONTH column
correlation_matrix <- cor(presalesData[, -1, with = FALSE])

# Extract the correlations for store 77
store_77_correlations <- correlation_matrix[77, ]

# Sort the correlations and exclude the correlation of store 77 with itself
sorted_correlations <- sort(store_77_correlations[store_77_correlations != 1], decreasing = TRUE)

# Get the top 10 highest correlations
top_corr_with_77 <- head(sorted_correlations, 10)

# View the store numbers and their correlations
top_corr_with_77

```

```{r}
salesdata <- as.data.frame(salesdata)
# Assuming 'salesdata' is your dataframe
# Loop over each column name in the dataframe
names(salesdata) <- sapply(names(salesdata), function(name) {
  # Check if the name is numeric by removing all non-digit characters and seeing if the name is still the same
  if (grepl("^[0-9]+$", name)) {
    return(paste0("store.", name))  # Add prefix if the name is numeric
  } else {
    return(name)  # Return the name as is if it's not numeric
  }
})
```


```{r}
final_sales_77 <- salesdata[,c("store.77","store.248", "store.93", "store.5", "store.229","store.234")]
final_sales_77 <- as.data.frame(final_sales_77)

impact <- CausalImpact(data = final_sales_77,
                       pre.period = c(start, treatment-1),
                       post.period = c(treatment, end))
plot(impact)
summary(impact)
```

```{r}
#Sales of Store 86
# Compute the correlation matrix excluding the YEARMONTH column
correlation_matrix <- cor(presalesData[, -1, with = FALSE])

# Extract the correlations for store 86
store_86_correlations <- correlation_matrix[86, ]

# Sort the correlations and exclude the correlation of store 86 with itself
sorted_correlations <- sort(store_86_correlations[store_86_correlations != 1], decreasing = TRUE)

# Get the top 10 highest correlations
top_corr_with_86 <- head(sorted_correlations, 10)

# View the store numbers and their correlations
top_corr_with_86
```


```{r}
final_sales_86 <- salesdata[,c("store.86","store.204", "store.161")]
final_sales_86 <- as.data.frame(final_sales_86)
set.seed(111)
impact <- CausalImpact(data = final_sales_86,
                       pre.period = c(start, treatment-1),
                       post.period = c(treatment, end))
plot(impact)
summary(impact)
```

```{r}
#Sales of Store 88
# Compute the correlation matrix excluding the YEARMONTH column
correlation_matrix <- cor(presalesData[, -1, with = FALSE])

# Extract the correlations for store 88
store_88_correlations <- correlation_matrix[88, ]

# Sort the correlations and exclude the correlation of store 88 with itself
sorted_correlations <- sort(store_88_correlations[store_88_correlations != 1], decreasing = TRUE)

# Get the top 10 highest correlations
top_corr_with_88 <- head(sorted_correlations, 10)

# View the store numbers and their correlations
top_corr_with_88
```

```{r}
final_sales_88 <- salesdata[,c("store.88","store.2", "store.95","store.224")]
final_sales_88 <- as.data.frame(final_sales_88)
set.seed(111)
impact <- CausalImpact(data = final_sales_88,
                       pre.period = c(start, treatment-1),
                       post.period = c(treatment, end))
plot(impact)
summary(impact)
```
```{r}
# Get number of customers data
# Use dcast to reshape the data
ncustData <- dcast(fullobsdata,YEARMONTH ~ STORE_NBR, value.var = "nCustomers")
prencustData <- ncustData[YEARMONTH < 201902]
# View the reshaped dataset
head(ncustData,2)
```

```{r}
# number of customers for store 77
# Compute the correlation matrix excluding the YEARMONTH column
correlation_matrix <- cor(prencustData[, -1, with = FALSE])

# Extract the correlations for store 77
store_77_correlations <- correlation_matrix[77, ]

# Sort the correlations and exclude the correlation of store 77 with itself
sorted_correlations <- sort(store_77_correlations[store_77_correlations != 1], decreasing = TRUE)

# Get the top 10 highest correlations
top_corr_with_77 <- head(sorted_correlations, 10)

# View the store numbers and their correlations
top_corr_with_77
```
```{r}
ncustData <- as.data.frame(ncustData)
# Loop over each column name in the dataframe
names(ncustData) <- sapply(names(ncustData), function(name) {
  # Check if the name is numeric by removing all non-digit characters and seeing if the name is still the same
  if (grepl("^[0-9]+$", name)) {
    return(paste0("store.", name))  # Add prefix if the name is numeric
  } else {
    return(name)  # Return the name as is if it's not numeric
  }
})
```

```{r}
final_ncust_77 <- ncustData[,c("store.77","store.40", "store.93", "store.10", "store.234","store.5","store.26")]
final_ncust_77 <- as.data.frame(final_ncust_77)
set.seed(111)
impact <- CausalImpact(data = final_ncust_77,
                       pre.period = c(start, treatment-1),
                       post.period = c(treatment, end))
plot(impact)
summary(impact)
```
```{r}
# number of customers for store 86
# Compute the correlation matrix excluding the YEARMONTH column
correlation_matrix <- cor(prencustData[, -1, with = FALSE])

# Extract the correlations for store 86
store_86_correlations <- correlation_matrix[86, ]

# Sort the correlations and exclude the correlation of store 86 with itself
sorted_correlations <- sort(store_86_correlations[store_86_correlations != 1], decreasing = TRUE)

# Get the top 10 highest correlations
top_corr_with_86 <- head(sorted_correlations, 10)

# View the store numbers and their correlations
top_corr_with_86
```
```{r}
final_ncust_86 <- ncustData[,c("store.86","store.125", "store.161")]

final_ncust_86 <- as.data.frame(final_ncust_86)

set.seed(111)
impact <- CausalImpact(data = final_ncust_86,
                       pre.period = c(start, treatment-1),
                       post.period = c(treatment, end))
plot(impact)
summary(impact)
```
```{r}
# number of customers for store 88
# Compute the correlation matrix excluding the YEARMONTH column
correlation_matrix <- cor(prencustData[, -1, with = FALSE])

# Extract the correlations for store 88
store_88_correlations <- correlation_matrix[88, ]

# Sort the correlations and exclude the correlation of store 88 with itself
sorted_correlations <- sort(store_88_correlations[store_88_correlations != 1], decreasing = TRUE)

# Get the top 10 highest correlations
top_corr_with_88 <- head(sorted_correlations, 10)

# View the store numbers and their correlations
top_corr_with_88
```

```{r}
final_ncust_88 <- ncustData[,c("store.88","store.200", "store.182","store.185","store.142")]

final_ncust_88 <- as.data.frame(final_ncust_88)

set.seed(111)
impact <- CausalImpact(data = final_ncust_88,
                       pre.period = c(start, treatment-1),
                       post.period = c(treatment, end))
plot(impact)
summary(impact)
```

